// Code generated by mockery v2.44.1. DO NOT EDIT.

package mocks

import (
	context "context"
	Domain "example/go-clean-architecture/Domain"

	mock "github.com/stretchr/testify/mock"
)

// TaskRepository is an autogenerated mock type for the TaskRepository type
type TaskRepository struct {
	mock.Mock
}

// CreateTask provides a mock function with given fields: ctx, task
func (_m *TaskRepository) CreateTask(ctx context.Context, task Domain.Task) (Domain.Task, error) {
	ret := _m.Called(ctx, task)

	if len(ret) == 0 {
		panic("no return value specified for CreateTask")
	}

	var r0 Domain.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, Domain.Task) (Domain.Task, error)); ok {
		return rf(ctx, task)
	}
	if rf, ok := ret.Get(0).(func(context.Context, Domain.Task) Domain.Task); ok {
		r0 = rf(ctx, task)
	} else {
		r0 = ret.Get(0).(Domain.Task)
	}

	if rf, ok := ret.Get(1).(func(context.Context, Domain.Task) error); ok {
		r1 = rf(ctx, task)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteTask provides a mock function with given fields: ctx, taskId
func (_m *TaskRepository) DeleteTask(ctx context.Context, taskId string) error {
	ret := _m.Called(ctx, taskId)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTask")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, taskId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindAlltasks provides a mock function with given fields: ctx
func (_m *TaskRepository) FindAlltasks(ctx context.Context) ([]Domain.Task, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for FindAlltasks")
	}

	var r0 []Domain.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]Domain.Task, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []Domain.Task); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Domain.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindTaskById provides a mock function with given fields: ctx, taskId
func (_m *TaskRepository) FindTaskById(ctx context.Context, taskId string) (Domain.Task, error) {
	ret := _m.Called(ctx, taskId)

	if len(ret) == 0 {
		panic("no return value specified for FindTaskById")
	}

	var r0 Domain.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (Domain.Task, error)); ok {
		return rf(ctx, taskId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) Domain.Task); ok {
		r0 = rf(ctx, taskId)
	} else {
		r0 = ret.Get(0).(Domain.Task)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, taskId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateTaskById provides a mock function with given fields: ctx, task, id
func (_m *TaskRepository) UpdateTaskById(ctx context.Context, task Domain.Task, id string) (Domain.Task, error) {
	ret := _m.Called(ctx, task, id)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTaskById")
	}

	var r0 Domain.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, Domain.Task, string) (Domain.Task, error)); ok {
		return rf(ctx, task, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, Domain.Task, string) Domain.Task); ok {
		r0 = rf(ctx, task, id)
	} else {
		r0 = ret.Get(0).(Domain.Task)
	}

	if rf, ok := ret.Get(1).(func(context.Context, Domain.Task, string) error); ok {
		r1 = rf(ctx, task, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewTaskRepository creates a new instance of TaskRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTaskRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *TaskRepository {
	mock := &TaskRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
